image: Visual Studio 2017

platform:
  - x64

# cache:
  # Not caching node_modules because appveyor doesn't restore it afterwards (not sure why)
  # - node_modules
  # - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - ps: xcopy /C /I /H /R /Y /S ReactNativeClient\lib ElectronClient\app\lib
  - npm install
  - npm run typescript-compile
  - ps: cd Tools
  - npm install
  - ps: cd ..\ElectronClient\app
  - npm install
  - yarn dist

test: off

# We only want to build tags
skip_non_tags: true