image: Visual Studio 2017

platform:
  - x64

# cache:
  # Not caching node_modules because appveyor doesn't restore it afterwards (not sure why)
  # - node_modules
  # - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - ps: cd ElectronClient\app
  - ps: xcopy /C /I /H /R /Y /S ..\..\ReactNativeClient\lib lib
  - npm install
  - yarn dist

test: off
