# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    app.eloquent:
        class: AppBundle\Eloquent
        arguments: ["%database%", '@app.mime_types', '@app.paths', '@app.cache']

    twig.exception_listener:
        class: stdObject

    app.paths:
        class: AppBundle\Paths
        arguments: ["%kernel.root_dir%"]

    app.mime_types:
        class: AppBundle\MimeTypes
        arguments: ['@app.paths']

    app.cache:
        class: AppBundle\Cache
        arguments: ["%kernel.cache_dir%"]
